#!/usr/bin/env python

import logging
import os
import soco
import time
from powermate import PowerMate


logger = logging.getLogger(__name__)
console_handler = logging.StreamHandler()
logger.addHandler(console_handler)


def set_light_on_volume():
    powermate.set_led_solid(int(sonos.volume * 0.392))


def on_turn(amount):
    '''wheel turned'''
    logger.debug(f'Turned: {amount}')
    sonos.volume += amount
    set_light_on_volume()


def on_button(pressed, doubleclick_delta=2.0):
    '''powermate button pressed or released'''
    global lastclick
    thisclick = time.time()
    if pressed:
        logger.debug(
            f'Button pressed - lastclick: {lastclick} - thisclick: {thisclick}')
        if (lastclick is None) or (thisclick - lastclick > doubleclick_delta):
            # single click
            status = sonos.get_current_transport_info()
            if status['current_transport_state'] == 'PLAYING':
                logger.debug('pausing')
                sonos.pause()
            else:
                logger.debug('playing')
                sonos.play()
            lastclick = thisclick
        else:
            # doubleclick - fast forward
            logger.debug('fast forward')
            sonos.next()
            sonos.play()
            lastclick = None  # reset doubleclick timer
    else:
        logger.debug('Button released')


def main():
    if os.getenv('SPDEBUG'):
        logger.setLevel(logging.DEBUG)
        logger.debug('DEBUG enabled')
    else:
        logger.setLevel(logging.INFO)
    global sonos, powermate, lastclick
    lastclick = None
    sonos = soco.discovery.any_soco()
    paths = PowerMate.enumerate()
    if not paths or not sonos:
        logger.error('No PowerMates / Sonos speakers detected')
    else:
        powermate = PowerMate(
            paths[0],
            turn_callback=on_turn,
            button_callback=on_button)
        powermate._loop.run_forever()


if __name__ == '__main__':
    main()
